type: object
properties:
  aerodynamics:
    type: object
    properties:
      lift_coefficient:
        type: number
        description: "Maximum lift coefficient"
      drag_coefficient:
        type: number
        description: "Drag coefficient at cruise"
  propulsion:
    type: object
    properties:
      thrust:
        type: number
        description: "Maximum thrust in Newtons"
      specific_fuel_consumption:
        type: number
        description: "SFC in g/kN-s"
  performance:
    type: object
    properties:
      range:
        type: number
        description: "Maximum range in kilometers"
      ceiling:
        type: number
        description: "Service ceiling in meters"
required: [aerodynamics, propulsion, performance]# schema.yaml
type: object
properties:
  aerodynamics:
    type: object
    properties:
      lift_coefficient:
        type: number
        description: "Maximum lift coefficient"
      drag_coefficient:
        type: number
        description: "Drag coefficient at cruise"
  propulsion:
    type: object
    properties:
      thrust:
        type: number
        description: "Maximum thrust in Newtons"
      specific_fuel_consumption:
        type: number
        description: "SFC in g/kN-s"
  performance:
    type: object
    properties:
      range:
        type: number
        description: "Maximum range in kilometers"
      ceiling:
        type: number
        description: "Service ceiling in meters"
required: [aerodynamics, propulsion, performance]
